export const SYLLABUS = {
  Physics: [
    { id: 'phy_1', name: 'Current Electricity', weight: 'High' },
    { id: 'phy_2', name: 'Semiconductor Electronics', weight: 'High' },
    { id: 'phy_3', name: 'Ray Optics & Optical Instruments', weight: 'High' },
    { id: 'phy_4', name: 'Electrostatic Potential & Capacitance', weight: 'High' },
    { id: 'phy_5', name: 'Thermodynamics', weight: 'High' },
    { id: 'phy_6', name: 'Alternating Current', weight: 'High' },
    { id: 'phy_7', name: 'Laws of Motion', weight: 'Medium' },
    { id: 'phy_8', name: 'Work, Energy and Power', weight: 'Medium' },
    { id: 'phy_9', name: 'System of Particles & Rotational Motion', weight: 'Medium' },
    { id: 'phy_10', name: 'Magnetic Effects of Current & Magnetism', weight: 'Medium' },
    { id: 'phy_11', name: 'Wave Optics', weight: 'Medium' },
    { id: 'phy_12', name: 'Dual Nature of Radiation & Matter', weight: 'Medium' },
    { id: 'phy_13', name: 'Units and Measurements', weight: 'Low' },
    { id: 'phy_14', name: 'Kinematics', weight: 'Low' },
    { id: 'phy_15', name: 'Gravitation', weight: 'Low' },
    { id: 'phy_16', name: 'Mechanical Properties of Solids & Fluids', weight: 'Low' },
    { id: 'phy_17', name: 'Oscillations & Waves', weight: 'Low' },
    { id: 'phy_18', name: 'Atoms & Nuclei', weight: 'Low' }
  ],
  Chemistry: [
    { id: 'che_1', name: 'Coordination Compounds', weight: 'High' },
    { id: 'che_2', name: 'Chemical Bonding & Molecular Structure', weight: 'High' },
    { id: 'che_3', name: 'Equilibrium', weight: 'High' },
    { id: 'che_4', name: 'p-Block Elements', weight: 'High' },
    { id: 'che_5', name: 'Aldehydes, Ketones & Carboxylic Acids', weight: 'High' },
    { id: 'che_6', name: 'General Organic Chemistry (GOC)', weight: 'High' },
    { id: 'che_7', name: 'Electrochemistry', weight: 'Medium' },
    { id: 'che_8', name: 'Chemical Kinetics', weight: 'Medium' },
    { id: 'che_9', name: 'Solutions', weight: 'Medium' },
    { id: 'che_10', name: 'd and f Block Elements', weight: 'Medium' },
    { id: 'che_11', name: 'Haloalkanes & Haloarenes', weight: 'Medium' },
    { id: 'che_12', name: 'Alcohols, Phenols & Ethers', weight: 'Medium' },
    { id: 'che_13', name: 'Amines', weight: 'Medium' },
    { id: 'che_14', name: 'Thermodynamics', weight: 'Low' },
    { id: 'che_15', name: 'Some Basic Concepts of Chemistry', weight: 'Low' },
    { id: 'che_16', name: 'Structure of Atom', weight: 'Low' },
    { id: 'che_17', name: 'Classification of Elements & Periodicity', weight: 'Low' },
    { id: 'che_18', name: 'Hydrocarbons', weight: 'Low' },
    { id: 'che_19', name: 'Biomolecules', weight: 'Low' }
  ],
  Botany: [
    { id: 'bot_1', name: 'Genetics & Evolution', weight: 'High' },
    { id: 'bot_2', name: 'Ecology & Environment', weight: 'High' },
    { id: 'bot_3', name: 'Cell: The Unit of Life', weight: 'High' },
    { id: 'bot_4', name: 'Plant Physiology', weight: 'Medium' },
    { id: 'bot_5', name: 'Sexual Reproduction in Flowering Plants', weight: 'Medium' },
    { id: 'bot_6', name: 'Morphology of Flowering Plants', weight: 'Medium' },
    { id: 'bot_7', name: 'Anatomy of Flowering Plants', weight: 'Low' },
    { id: 'bot_8', name: 'Biological Classification', weight: 'Low' },
    { id: 'bot_9', name: 'Plant Kingdom', weight: 'Low' }
  ],
  Zoology: [
    { id: 'zoo_1', name: 'Human Physiology', weight: 'High' },
    { id: 'zoo_2', name: 'Human Reproduction & Reproductive Health', weight: 'High' },
    { id: 'zoo_3', name: 'Biotechnology & Its Applications', weight: 'High' },
    { id: 'zoo_4', name: 'Animal Kingdom', weight: 'Medium' },
    { id: 'zoo_5', name: 'Structural Organisation in Animals', weight: 'Medium' },
    { id: 'zoo_6', name: 'Human Health & Disease', weight: 'Medium' },
    { id: 'zoo_7', name: 'Evolution', weight: 'Low' },
    { id: 'zoo_8', name: 'Biomolecules', weight: 'Low' }
  ]
};
